// Vehicle models built by scripts/vehicles/make-vehicles.swift, as glTF
// binaries for Android (Metro picks this file there, so Android bundles only
// the .glb files and iOS only the .usdz ones; paint is recoloured with
// `tint`). Import from 'munim-maps/vehicles' so apps that do not use them do
// not bundle them.
module.exports.VEHICLES = {
  'balloon': require('./vehicles/glb/balloon.glb'),
  'bike-city': require('./vehicles/glb/bike-city.glb'),
  'bike-mountain': require('./vehicles/glb/bike-mountain.glb'),
  'bike-road': require('./vehicles/glb/bike-road.glb'),
  'boat-jetski': require('./vehicles/glb/boat-jetski.glb'),
  'boat-sail': require('./vehicles/glb/boat-sail.glb'),
  'boat-speed': require('./vehicles/glb/boat-speed.glb'),
  'boat-yacht': require('./vehicles/glb/boat-yacht.glb'),
  'bus-city': require('./vehicles/glb/bus-city.glb'),
  'bus-school': require('./vehicles/glb/bus-school.glb'),
  'car-convertible': require('./vehicles/glb/car-convertible.glb'),
  'car-ev': require('./vehicles/glb/car-ev.glb'),
  'car-hatchback': require('./vehicles/glb/car-hatchback.glb'),
  'car-minivan': require('./vehicles/glb/car-minivan.glb'),
  'car-offroader': require('./vehicles/glb/car-offroader.glb'),
  'car-pickup': require('./vehicles/glb/car-pickup.glb'),
  'car-police': require('./vehicles/glb/car-police.glb'),
  'car-sedan': require('./vehicles/glb/car-sedan.glb'),
  'car-sports': require('./vehicles/glb/car-sports.glb'),
  'car-supercar': require('./vehicles/glb/car-supercar.glb'),
  'car-suv': require('./vehicles/glb/car-suv.glb'),
  'car-taxi': require('./vehicles/glb/car-taxi.glb'),
  'car-wagon': require('./vehicles/glb/car-wagon.glb'),
  'heli-light': require('./vehicles/glb/heli-light.glb'),
  'jet-f16': require('./vehicles/glb/jet-f16.glb'),
  'jet-f22': require('./vehicles/glb/jet-f22.glb'),
  'jet-f35': require('./vehicles/glb/jet-f35.glb'),
  'jet-yf23': require('./vehicles/glb/jet-yf23.glb'),
  'motorcycle-cruiser': require('./vehicles/glb/motorcycle-cruiser.glb'),
  'motorcycle-dirt': require('./vehicles/glb/motorcycle-dirt.glb'),
  'motorcycle-sport': require('./vehicles/glb/motorcycle-sport.glb'),
  'plane-airliner': require('./vehicles/glb/plane-airliner.glb'),
  'plane-jet': require('./vehicles/glb/plane-jet.glb'),
  'plane-prop': require('./vehicles/glb/plane-prop.glb'),
  'plane-widebody': require('./vehicles/glb/plane-widebody.glb'),
  'rail-highspeed': require('./vehicles/glb/rail-highspeed.glb'),
  'rail-tram': require('./vehicles/glb/rail-tram.glb'),
  'rocket-falcon9': require('./vehicles/glb/rocket-falcon9.glb'),
  'rocket-saturnv': require('./vehicles/glb/rocket-saturnv.glb'),
  'rocket-shuttle': require('./vehicles/glb/rocket-shuttle.glb'),
  'rocket-starship': require('./vehicles/glb/rocket-starship.glb'),
  'satellite-cubesat': require('./vehicles/glb/satellite-cubesat.glb'),
  'satellite-dragon': require('./vehicles/glb/satellite-dragon.glb'),
  'satellite-gps': require('./vehicles/glb/satellite-gps.glb'),
  'satellite-hubble': require('./vehicles/glb/satellite-hubble.glb'),
  'satellite-iss': require('./vehicles/glb/satellite-iss.glb'),
  'satellite-jwst': require('./vehicles/glb/satellite-jwst.glb'),
  'satellite-starlink': require('./vehicles/glb/satellite-starlink.glb'),
  'scooter-kick': require('./vehicles/glb/scooter-kick.glb'),
  'scooter-moped': require('./vehicles/glb/scooter-moped.glb'),
  'starbase-mount': require('./vehicles/glb/starbase-mount.glb'),
  'starbase-tower': require('./vehicles/glb/starbase-tower.glb'),
  'truck-box': require('./vehicles/glb/truck-box.glb'),
  'truck-fire': require('./vehicles/glb/truck-fire.glb'),
  'truck-semi': require('./vehicles/glb/truck-semi.glb'),
  'van-ambulance': require('./vehicles/glb/van-ambulance.glb'),
  'van-delivery': require('./vehicles/glb/van-delivery.glb'),
}

module.exports.VEHICLE_NAMES = Object.keys(module.exports.VEHICLES)
