// Vehicle models built by scripts/vehicles/make-vehicles.swift (paint is
// recoloured with `tint`). Import from 'munim-maps/vehicles' so apps that do
// not use them do not bundle them.
module.exports.VEHICLES = {
  'balloon': require('./vehicles/balloon.usdz'),
  'bike-city': require('./vehicles/bike-city.usdz'),
  'bike-mountain': require('./vehicles/bike-mountain.usdz'),
  'bike-road': require('./vehicles/bike-road.usdz'),
  'boat-jetski': require('./vehicles/boat-jetski.usdz'),
  'boat-sail': require('./vehicles/boat-sail.usdz'),
  'boat-speed': require('./vehicles/boat-speed.usdz'),
  'boat-yacht': require('./vehicles/boat-yacht.usdz'),
  'bus-city': require('./vehicles/bus-city.usdz'),
  'bus-school': require('./vehicles/bus-school.usdz'),
  'car-convertible': require('./vehicles/car-convertible.usdz'),
  'car-ev': require('./vehicles/car-ev.usdz'),
  'car-hatchback': require('./vehicles/car-hatchback.usdz'),
  'car-minivan': require('./vehicles/car-minivan.usdz'),
  'car-offroader': require('./vehicles/car-offroader.usdz'),
  'car-pickup': require('./vehicles/car-pickup.usdz'),
  'car-police': require('./vehicles/car-police.usdz'),
  'car-sedan': require('./vehicles/car-sedan.usdz'),
  'car-sports': require('./vehicles/car-sports.usdz'),
  'car-supercar': require('./vehicles/car-supercar.usdz'),
  'car-suv': require('./vehicles/car-suv.usdz'),
  'car-taxi': require('./vehicles/car-taxi.usdz'),
  'car-wagon': require('./vehicles/car-wagon.usdz'),
  'heli-light': require('./vehicles/heli-light.usdz'),
  'jet-f16': require('./vehicles/jet-f16.usdz'),
  'jet-f22': require('./vehicles/jet-f22.usdz'),
  'jet-f35': require('./vehicles/jet-f35.usdz'),
  'jet-yf23': require('./vehicles/jet-yf23.usdz'),
  'motorcycle-cruiser': require('./vehicles/motorcycle-cruiser.usdz'),
  'motorcycle-dirt': require('./vehicles/motorcycle-dirt.usdz'),
  'motorcycle-sport': require('./vehicles/motorcycle-sport.usdz'),
  'plane-airliner': require('./vehicles/plane-airliner.usdz'),
  'plane-jet': require('./vehicles/plane-jet.usdz'),
  'plane-prop': require('./vehicles/plane-prop.usdz'),
  'plane-widebody': require('./vehicles/plane-widebody.usdz'),
  'rail-highspeed': require('./vehicles/rail-highspeed.usdz'),
  'rail-tram': require('./vehicles/rail-tram.usdz'),
  'rocket-falcon9': require('./vehicles/rocket-falcon9.usdz'),
  'rocket-saturnv': require('./vehicles/rocket-saturnv.usdz'),
  'rocket-shuttle': require('./vehicles/rocket-shuttle.usdz'),
  'rocket-starship': require('./vehicles/rocket-starship.usdz'),
  'scooter-kick': require('./vehicles/scooter-kick.usdz'),
  'scooter-moped': require('./vehicles/scooter-moped.usdz'),
  'truck-box': require('./vehicles/truck-box.usdz'),
  'truck-fire': require('./vehicles/truck-fire.usdz'),
  'truck-semi': require('./vehicles/truck-semi.usdz'),
  'van-ambulance': require('./vehicles/van-ambulance.usdz'),
  'van-delivery': require('./vehicles/van-delivery.usdz'),
}

module.exports.VEHICLE_NAMES = Object.keys(module.exports.VEHICLES)
